name: Solicitar Funcionalidade
description: Sugira uma ideia para este projeto
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Sua sugestão está relacionada a um problema?
      description: Uma descrição clara e concisa do problema. Ex. Eu sempre fico frustrado quando [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Descreva a solução que você gostaria
      description: Uma descrição clara e concisa do que você quer que aconteça.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Descreva as alternativas que você considerou
      description: Uma descrição clara e concisa de quaisquer soluções alternativas ou funcionalidades que você considerou.
  - type: textarea
    id: context
    attributes:
      label: Contexto adicional
      description: Adicione qualquer outro contexto ou capturas de tela sobre o pedido de funcionalidade aqui.
